steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/backend-gestion-personal:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/backend-gestion-personal:latest',
      '.'
    ]

  # Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-gestion-personal:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-gestion-personal:latest']

  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'backend-gestion-personal',
      '--image', 'gcr.io/$PROJECT_ID/backend-gestion-personal:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '0',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production'
    ]

# Configuración de imágenes
images:
  - 'gcr.io/$PROJECT_ID/backend-gestion-personal:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/backend-gestion-personal:latest'

# Opciones de build
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

